# Generated by Django 5.2.17 on 2026-09-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RETRY', 'Retry'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.notification')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'subscription'), name='unique_notification_push_subscription')],
            },
        ),
    ]
