# Generated by Django 5.2.17 on 2026-09-25 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('organization_name', models.CharField(max_length=160)),
                ('app_name', models.CharField(default='NEXORA', max_length=80)),
                ('short_app_name', models.CharField(default='NEXORA', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=18)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#315EFB', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use #RRGGBB.')])),
                ('secondary_color', models.CharField(default='#101828', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use #RRGGBB.')])),
                ('privacy_policy', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('community_rules', models.TextField(blank=True)),
                ('data_policy', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
