# Generated by Django 5.2.17 on 2026-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('LOGO', 'Logo'), ('FAVICON', 'Favicon')], max_length=10, unique=True)),
                ('storage_key', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='allow_delete_everyone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='allow_member_name_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='max_image_size_mb',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='max_message_length',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='max_video_size_mb',
            field=models.PositiveSmallIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='max_voice_duration_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='message_delete_window_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='message_edit_window_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
