# Generated by Django 5.2.17 on 2026-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_messagedeletion_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='optimized_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='attachment',
            name='processing_error',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='attachment',
            name='processing_state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('READY', 'READY'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
