# Generated by Django 5.2.17 on 2026-09-25 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_attachment_optimized_key_attachment_processing_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', False), ('kind', 'ADMIN_PRIVATE'), ('member__isnull', False)), models.Q(('admin__isnull', False), ('kind', 'GROUP'), ('member__isnull', True)), _connector='OR'), name='valid_conversation_shape'),
        ),
    ]
