# Generated by Django 5.2.17 on 2026-09-26 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_valid_conversation_shape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='processing_state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('RETRY', 'RETRY'), ('READY', 'READY'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'type', '-created_at'], name='conversatio_convers_de7817_idx'),
        ),
    ]
