# Generated by Django 5.2.17 on 2026-09-26 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_attachment_next_attempt_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagereceipt',
            index=models.Index(fields=['recipient', 'read_at'], name='receipt_recipient_unread_idx'),
        ),
    ]
