# Generated by Django 5.2.17 on 2026-09-26 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0005_attachment_next_attempt_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=10)),
                ('client_id', models.CharField(max_length=64)),
                ('declared_name', models.CharField(blank=True, max_length=160)),
                ('declared_size', models.PositiveBigIntegerField()),
                ('part_size', models.PositiveIntegerField()),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('next_part', models.PositiveIntegerField(default=0)),
                ('staging_key', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted')], db_index=True, default='OPEN', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'expires_at'], name='media_uploa_state_2d5a57_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='unique_user_upload_client_id')],
            },
        ),
    ]
