# Generated by Django 5.2.17 on 2026-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_can_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='members_can_react',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members_can_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members_can_send_media',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members_can_send_voice',
            field=models.BooleanField(default=True),
        ),
    ]
