# Generated by Django 5.2.17 on 2026-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_members_can_leave_group_members_can_react_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
